package com.brkv.travelfinder

import android.content.Context
import android.content.SharedPreferences
import android.os.Bundle
import android.view.View
import androidx.appcompat.app.AppCompatActivity
import androidx.fragment.app.Fragment
import androidx.fragment.app.FragmentManager
import androidx.fragment.app.FragmentTransaction
import com.brkv.travelfinder.fragments.Card
import com.google.android.material.tabs.TabLayout
import org.jetbrains.anko.doAsync


class MainActivity : AppCompatActivity() {
    companion object { const val PREF_NB = "PREF_NB" }
    val articleDb by lazy { ArticleDb(ArticleDbHelper(applicationContext)) }
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        val tabLayout = findViewById<View>(R.id.tabLayout) as TabLayout
        val sharedPref = getPreferences(Context.MODE_PRIVATE)
        val editor: SharedPreferences.Editor = sharedPref.edit()
        changeFrag(Card(query("Europe")))

        if(sharedPref.contains(PREF_NB)){
            editor.putInt(PREF_NB, sharedPref.getInt(PREF_NB,0)+1)
            editor.commit()
        }
        else {
            editor.putInt(PREF_NB, 0)
            initDb()
            editor.commit()
        }

        tabLayout.addOnTabSelectedListener(object : TabLayout.OnTabSelectedListener {

            override fun onTabSelected(tab: TabLayout.Tab?) {
                var fragment: Fragment = Card(query("Europe"))
                when (tab!!.position) {
                    0 -> fragment = Card(query("Europe"))
                    1 -> fragment = Card(query("Asie"))
                    2 -> fragment = Card(query("Amérique"))
                    3 -> fragment = Card(query("Afrique"))
                    4 -> fragment = Card(query("Océanie"))
                }
                changeFrag(fragment)
            }


            override fun onTabReselected(tab: TabLayout.Tab?) {

            }

            override fun onTabUnselected(tab: TabLayout.Tab?) {

            }
        })
    }

    private fun changeFrag(fragment : Fragment){
        val fm: FragmentManager = supportFragmentManager
        val ft: FragmentTransaction = fm.beginTransaction()
        ft.replace(R.id.frameLayout, fragment)
        ft.setTransition(FragmentTransaction.TRANSIT_FRAGMENT_OPEN)
        ft.commit()
    }

    private fun initDb() {
        doAsync {
            var article1 = Article("Londres","Londres est la capitale et la plus grande ville d'Angleterre et du Royaume-Uni. La ville est située près de l'estuaire de la Tamise dans le sud-est de l'Angleterre. La ville exerce un impact considérable sur les arts, le commerce, l'éducation, le divertissement, la mode, les finances, les soins de santé, les médias, les services professionnels, la recherche et le développement, le tourisme et les transports.", "https://images.pexels.com/photos/460672/pexels-photo-460672.jpeg", "London", "Europe")
            var article2 = Article("Paris","Paris est la ville la plus peuplée et la capitale de la France. Elle se situe au cœur d'un vaste bassin sédimentaire aux sols fertiles et au climat tempéré, le bassin parisien, sur une boucle de la Seine, entre les confluents de celle-ci avec la Marne et l'Oise. Paris est également le chef-lieu de la région Île-de-France et le centre de la métropole du Grand Paris, créée en 2016. Elle est divisée en arrondissements, comme les villes de Lyon et de Marseille, au nombre de vingt. ", "https://images.pexels.com/photos/149637/pexels-photo-149637.jpeg", "Paris", "Europe")
            var article3 = Article("Berlin","Berlin est la capitale et la plus grande ville d'Allemagne. Institutionnellement, c’est une ville-État nommée Land de Berlin. Située dans le Nord-Est du pays, Berlin compte environ 3,8 millions d'habitants. Ses habitants s'appellent les Berlinois et les Berlinoises (die Berliner et die Berlinerinnen en allemand). Elle est la première ville et la huitième agglomération la plus peuplée de l'Union européenne.", "https://images.pexels.com/photos/1057840/pexels-photo-1057840.jpeg", "Berlin", "Europe")
            var article4 = Article("Amsterdam","Amsterdam est la capitale des Pays-Bas, bien que le gouvernement ainsi que la plupart des institutions nationales siègent à La Haye. Sur la base des chiffres de l'année 2017, la commune d'Amsterdam compte plus de 850 000 habitants, appelés Amstellodamois, ce qui en fait la commune néerlandaise la plus peuplée. ", "https://images.pexels.com/photos/2031706/pexels-photo-2031706.jpeg", "Amsterdam", "Europe")
            var article5 = Article("Venise","Venise est une ville côtière du nord-est de l'Italie, sur les rives de la mer Adriatique. Elle s'étend sur un ensemble de 121 petites îles séparées par un réseau de canaux et reliées par 435 ponts. Située au milieu de la lagune vénète, entre les estuaires du Pô et du Piave, Venise est renommée pour cet emplacement exceptionnel ainsi que pour son architecture et son patrimoine culturel, qui lui valent une inscription au patrimoine mondial de l'UNESCO.", "https://images.pexels.com/photos/1796736/pexels-photo-1796736.jpeg", "Venice", "Europe")
            var article6 = Article("Barcelone","Barcelone est la capitale administrative et économique de la Catalogne, de la province de Barcelone, de la comarque du Barcelonès ainsi que de son aire et de sa région métropolitaines, en Espagne. Barcelone est la deuxième ville d'Espagne au regard de la population, de l'économie et des activités, la onzième ville la plus peuplée de l'Union européenne et la sixième en incluant sa banlieue : en 2018, 4,84 millions de personnes vivent dans l'agglomération barcelonaise. La majeure partie des municipalités adjacentes sont en outre rassemblées dans l'Aire métropolitaine de Barcelone. \n", "https://images.pexels.com/photos/1388030/pexels-photo-1388030.jpeg", "Barcelona", "Europe")
            var article7 = Article("Prague","Prague est la capitale et la plus grande ville de la Tchéquie, en Bohême. Située au cœur de l'Europe centrale, à l'ouest du pays, la ville est édifiée sur les rives de la Vltava (en allemand : Moldau). Capitale historique du royaume de Bohême, berceau du peuple tchèque, Prague connaît son apogée au XIVe siècle, sous le règne du roi de Bohême et empereur germanique Charles IV qui en fait la capitale de l'Empire. Elle est alors un centre culturel et religieux de première importance.", "https://images.pexels.com/photos/61381/pexels-photo-61381.jpeg", "Prague", "Europe")
            var article8 = Article("Budapest","Budapest est la plus grande ville et la capitale de la Hongrie. Elle se situe en aval du coude du Danube entre le massif de Transdanubie et l'Alföld. Ses habitants sont les Budapestois. La ville actuelle est créée en 1873 par la fusion de Buda — alors capitale de la Hongrie — de Pest et d'Óbuda. Elle a pour origine le site d'Aquincum, un point de peuplement celte devenu capitale de la Pannonie inférieure pendant l'époque romaine.", "https://images.pexels.com/photos/732057/pexels-photo-732057.jpeg", "Budapest", "Europe")
            var article9 = Article("Lisbonne","Lisbonne est la capitale et la plus grande ville du Portugal. Considérée comme une « ville mondiale » selon le classement 2010 du Réseau d’étude sur la mondialisation et les villes mondiales comme Taipei, Miami, Varsovie ou Munich, Lisbonne est également le chef-lieu du district de Lisbonne, du Grand Lisbonne et de la zone métropolitaine de Lisbonne. Ses habitants sont habituellement appelés Lisboètes (du portugais lisboeta), mais on rencontre aussi les termes Lisbonnin et Lisbonnais. ", "https://images.pexels.com/photos/9253/sea-city-landscape-sky.jpg", "Lisbon", "Europe")
            var article10 = Article("Reykjavik","Reykjavik est la capitale de l'Islande. Elle se situe à environ 250 km au sud du cercle polaire arctique, ce qui en fait la capitale la plus septentrionale d'un État souverain (la capitale du Groenland, Nuuk, étant située quelques kilomètres plus au nord). Elle s'étale entre deux fjords, dans une zone comptant de nombreuses sources chaudes, le long d'une baie. Elle est ainsi considérée comme la ville la « plus verte du monde » : on y compte environ 410 m2 d'espaces verts par habitant.", "https://images.pexels.com/photos/831058/pexels-photo-831058.jpeg", "Reykjavik", "Europe")
            val list_europe = listOf<Article>(article1,article2,article3,article4,article5,article6,article7,article8,article9,article10)
           articleDb.saveArticles(list_europe)
            article1 = Article("New York","New York, officiellement nommée City of New York, connue également sous les noms et abréviations de New York City ou NYC (pour éviter la confusion avec l'État de New York), et dont le surnom le plus connu est The Big Apple, est la plus grande ville des États-Unis en nombre d'habitants et l'une des plus importantes du continent américain. Elle se situe dans le Nord-Est du pays, sur la côte atlantique, à l'extrémité sud-est de l'État de New York. La ville de New York se compose de cinq arrondissements appelés boroughs : Manhattan, Brooklyn, Queens, le Bronx et Staten Island. Ses habitants s'appellent les New-Yorkais", "https://images.pexels.com/photos/466685/pexels-photo-466685.jpeg", "New York", "Amérique")
            article2 = Article("San Fransisco","San Francisco, officiellement « ville et comté de San Francisco » (en anglais : « City and County of San Francisco »), est une ville des États-Unis et l'un des comtés de l'État de Californie. Elle est située à l'extrémité nord de la péninsule de San Francisco, entre l'océan Pacifique à l'ouest et la baie de San Francisco à l'est. Son nom est couramment abrégé en « SF » et la ville est surnommée « The City by the Bay ».", "https://images.pexels.com/photos/1141853/pexels-photo-1141853.jpeg", "San Fransisco", "Amérique")
            article3 = Article("Las Vegas","Las Vegas est une ville américaine, plus grande ville de l'État du Nevada et centre économique et touristique majeur de l'Ouest des États-Unis. En 2017, elle compte une population de 648 224 habitants. Elle est située au milieu du désert des Mojaves, le plus sec des quatre déserts nord-américains, dans le comté de Clark. La ville fondée en 1855, devient au début du XXe siècle une bourgade agricole. Grâce aux lois libérales en matière de jeux de l'État, la ville acquiert une renommée mondiale pour ses casinos.", "https://images.pexels.com/photos/2837909/pexels-photo-2837909.jpeg", "Las Vegas", "Amérique")
            article4 = Article("Toronto","Toronto est la ville la plus peuplée du Canada et la capitale de la province de l'Ontario. Elle se situe dans le Sud-Est du Canada, sur la rive nord-ouest du lac Ontario. Selon le recensement de 2016, Toronto compte plus de 2,7 millions d'habitants, faisant d'elle la quatrième ville la plus peuplée en Amérique du Nord. Son aire métropolitaine compte 5,9 millions d'habitants, et la mégalopole du Golden Horseshoe, dont elle est le cœur, plus de 8,7 millions d'habitants en 2011, soit le quart de la population canadienne.", "https://images.pexels.com/photos/1519088/pexels-photo-1519088.jpeg", "Toronto", "Amérique")
            article5 = Article("Mexico","Mexico est une entité fédérative1 et la capitale du Mexique. Cette entité fédérative n'est ni une ville ni un État au sens des articles 43, 44 et 122 de la Constitution mexicaine. Mexico est un centre financier et culturel important avec une économie agricole très présente dans les périphéries. Fondée au début du XIVe siècle par les Mexicas sur un îlot du lac Texcoco, la ville précolombienne de Tenochtitlan a été remplacée par les conquérants espagnols lors de la chute de l'Empire aztèque en 1521 par la première grande ville de tracé européen du continent.", "https://images.pexels.com/photos/1720086/pexels-photo-1720086.jpeg", "Mexico", "Amérique")
            article6 = Article("Lima","Lima est la capitale et la plus grande ville du Pérou, ainsi que le chef-lieu de la région de Lima. Au milieu de la façade maritime du Pérou sur l'océan Pacifique, Lima s'étend sur les vallées de trois fleuves : Rímac, Chillón et Lurín. Avec une agglomération d’environ dix millions d’habitants, Lima est la cinquième plus grande ville d'Amérique latine, derrière Mexico, São Paulo, Buenos Aires et Rio de Janeiro. Ses habitants s'appellent les Liméniens et Liméniennes.", "https://images.pexels.com/photos/1570610/pexels-photo-1570610.jpeg", "Lima", "Amérique")
            article7 = Article("San José","San José est la capitale et la plus grande ville du Costa Rica. Elle est également la capitale de la province de San José. Fondée en 1738, la ville devient capitale du Costa Rica en 1823 à la place de Cartago. La population de la municipalité de San José (canton de San José) était estimée à 333 981 habitants en 2015. Selon les Nations unies, l'agglomération métropolitaine de San José concentrait 1 975 000 habitants en 2009, soit environ 29 % de la population totale du Costa Rica ", "https://images.pexels.com/photos/3066240/pexels-photo-3066240.jpeg", "San José,CR", "Amérique")
            article8 = Article("La Havane","La Havane est la capitale et le centre économique de Cuba. Cette ville portuaire est aussi l'une des quinze provinces cubaines. La ville/province compte 2,4 millions d'habitants, tandis que l'agglomération en compte plus de 3,7 millions, ce qui fait de La Havane la plus grande ville des Caraïbes. La ville s'étend sur plus de 720 kilomètres carrés principalement à l'ouest et au sud d'une baie, à laquelle on accède par un passage étroit, et qui est divisé en trois ports : Marimelena, Guanabacoa et Atarés.", "https://images.pexels.com/photos/3687922/pexels-photo-3687922.jpeg", "La Havana", "Amérique")
            article9 = Article("Rio de Janeiro","Rio de Janeiro, souvent désignée simplement sous le nom de Rio, est la deuxième plus grande ville du Brésil après São Paulo. Située dans le Sud-Est du pays, elle est la capitale de l'État de Rio de Janeiro. Avec ses 6,1 millions d'habitants intra-muros (communément appelés Cariocas, la variante Carioques existant aussi en français) et 12,62 millions dans l'aire urbaine, Rio de Janeiro est l'une des métropoles les plus importantes du continent américain. ", "https://images.pexels.com/photos/2868242/pexels-photo-2868242.jpeg", "Rio de Janeiro", "Amérique")
            article10 = Article("Montréal","Montréal, en forme longue la Ville de Montréal, est la plus importante ville du Québec et la deuxième ville la plus peuplée du Canada, après Toronto et avant Vancouver. Elle se situe principalement sur l’île fluviale de Montréal, sur le fleuve Saint-Laurent (entre Québec et le lac Ontario) dans le Sud du Québec, dont elle est la métropole. Lors du recensement du Canada de 2016, la ville compte 1 704 694 habitants. Son aire urbaine, appelée la Région métropolitaine de Montréal, englobe plus de 4 millions d'habitants, soit environ la moitié de la population du Québec.", "https://images.pexels.com/photos/2244823/pexels-photo-2244823.jpeg", "Montreal", "Amérique")
            val list_amerique = listOf<Article>(article1,article2,article3,article4,article5,article6,article7,article8,article9,article10)
            articleDb.saveArticles(list_amerique)
            article1 = Article("Le Cap","Le Cap est une ville d'Afrique du Sud, capitale de la colonie du Cap (1652-1910) puis de la province du Cap (1910-1994). Elle est actuellement la capitale provinciale du Cap-Occidental. Depuis 1910, Le Cap est également la capitale parlementaire du pays aux côtés de Pretoria (capitale administrative) et de Bloemfontein (capitale judiciaire). La ville du Cap, fondée en 1652, est considérée comme la cité-mère d'Afrique du Sud.", "https://images.pexels.com/photos/259447/pexels-photo-259447.jpeg", "Cape Town", "Afrique")
            article2 = Article("Marrakech","Marrakech, est une ville située dans le centre du Maroc au pied des montagnes de l'Atlas. Marrakech est surnommée « la ville rouge »ou la « ville ocre » en référence à la couleur rouge d'une grande partie de ses immeubles et ses maisons. Marrakech et son aire urbaine comptent en 2020 un peu plus d'un million d'habitantsN 2. Par sa population, la ville est la troisième agglomération du pays, à égalité avec sa rivale historique, Fès. ", "https://images.pexels.com/photos/5155950/pexels-photo-5155950.jpeg", "Marrakech", "Afrique")
            article3 = Article("Le Caire","Le Caire est la capitale et la plus grande ville d'Égypte. Sa population est d'environ dix millions d'habitants. Elle serait également la sixième agglomération du monde en 2015. Carrefour du Moyen-Orient et de l'Afrique situé en amont du delta du Nil, sur les rives du fleuve ainsi que sur quelques îles adjacentes, elle se trouve au nord du pays, à 178 km au sud-est d'Alexandrie et 127 km à l'ouest du canal de Suez. Les habitants du Caire sont appelés les Cairotes.", "https://images.pexels.com/photos/3689859/pexels-photo-3689859.jpeg", "Cairo", "Afrique")
            article4 = Article("Victoria","Victoria est la capitale et la plus grande ville des Seychelles. Elle est située sur la côte nord-est de l'île de Mahé, île principale de l'archipel. Cette capitale de 24 701 habitants concentre plus d'un tiers de la population seychelloise. Avec une population de 24 701 habitants, Victoria concentre plus d'un tiers de la population totale de l'île. La ville de Victoria s'ouvre sur une large baie, à l'abri du Morne Seychellois et des Trois Frères. ", "https://images.pexels.com/photos/5048704/pexels-photo-5048704.jpeg", "Amsterdam", "Afrique")
            article5 = Article("Casablanca","Casablanca est une ville située au centre-ouest du Maroc. Capitale économique du pays et plus grande ville du Maghreb par la population, elle est située sur la côte atlantique, à environ 80 km au sud de Rabat, la capitale administrative. Sur le plan administratif, son territoire — à distinguer de celui de l'agglomération incluant sa banlieue — d'une superficie de 384 km2, correspond à celui de la préfecture de Casablanca, chef-lieu de la région Casablanca-Settat.", "https://images.pexels.com/photos/2404046/pexels-photo-2404046.jpeg", "Casablanca", "Afrique")
            article6 = Article("Gizeh","Gizeh, est une ville d'Égypte, située sur la rive gauche du Nil, face à la vieille ville du Caire. La renommée internationale de Gizeh est due aux célèbres grandes pyramides de Khéops, Khéphren et Mykérinos, ainsi qu'au Sphinx, témoins de la civilisation égyptienne antique au cours de l'Ancien Empire (~ 2700 – ~ 2200 AEC), situés sur le plateau à quelques kilomètres de la ville. C'est du pied de ces pyramides que Bonaparte, lors de la campagne d'Égypte, le 21 juillet 1798, avant une bataille décisive, aurait prononcé le célèbre « Soldats, songez que du haut de ces pyramides, quarante siècles vous contemplent. »", "https://images.pexels.com/photos/2402926/pexels-photo-2402926.jpeg", "Gizeh", "Afrique")
            article7 = Article("Durban","Durban est une ville d'Afrique du Sud située dans la province du KwaZulu-Natal au bord de l'océan Indien. Elle est l'ancienne capitale de la colonie et de la province du Natal. Durban est située sur le littoral de l'Océan Indien. Durban compte plus de 1 100 000 habitants au sein d'une métropole de près de 3,5 millions d'habitants dont 68,5 % de noirs, 20 % d'indiens, 9 % de blancs et 2,5 % d'asiatiques. La majorité des habitants sont de langue maternelle zouloue, suivies par les minorités de langue anglaise et afrikaans.", "https://images.pexels.com/photos/3814231/pexels-photo-3814231.jpeg", "Durban", "Afrique")
            article8 = Article("Tananarive","Tananarive est la capitale économique et politique de Madagascar, de la province d'Antananarivo et de la région Analamanga située dans la partie centrale de l'île. Ses habitants s'appellent les Antananariviens. Sa population dépasse 1 600 000 habitants, son aire urbaine approche les 2,2 millions d'habitants. La ville est divisée en six arrondissements et 192 fokontany. La ville fut tout d'abord construite comme une forteresse vers le début du XVIIe siècle par les rois Merina, qui en ont fait leur résidence principale dans les années 1790.", "https://images.pexels.com/photos/5017881/pexels-photo-5017881.jpeg", "Tananarive", "Afrique")
            article9 = Article("Tenerife","Tenerife, est une île d'Espagne faisant partie de l'archipel des îles Canaries, situées dans l'océan Atlantique. Il s'agit de la plus grande île de cet archipel mais aussi de la plus haute, le Teide constituant le point culminant de l'Espagne avec 3 718 mètres d'altitude. Tenerife est également l'île la plus étendue et la plus peuplée de la Macaronésie. Ses 917 841 habitants font d'elle l'île la plus peuplée d'Espagne et la plus urbanisée et cosmopolite des îles Canaries.", "https://images.pexels.com/photos/1606603/pexels-photo-1606603.jpeg", "Tenerife", "Afrique")
            article10 = Article("Zanzibar","Zanzibar est la ville de Tanzanie la plus importante de l'archipel de Zanzibar, le centre commercial et la capitale administrative du Gouvernement révolutionnaire de Zanzibar et de la région d'Unguja Ville et Ouest. Elle est située sur la côte occidentale de l'île d'Unguja. Elle s'étend également sur les sites de Ng'ambo et la vieille crique de Darajani. La vieille ville historique se nomme « Mji Mkongwe », plus connue sous son nom anglais Stone Town, la « ville de pierre », parce que ses maisons sont bâties en pierre de corail.", "https://images.pexels.com/photos/3361818/pexels-photo-3361818.jpeg", "Zanzibar", "Afrique")
            val list_afrique = listOf<Article>(article1,article2,article3,article4,article5,article6,article7,article8,article9,article10)
            articleDb.saveArticles(list_afrique)
            article1 = Article("Tokyo","Tokyo, anciennement Edo, officiellement Métropole de Tokyo, est de facto la capitale actuelle du Japon. Elle est la plus peuplée des préfectures du Japon, avec plus de 13 831 421 habitants intra-muros en 2018 et 42 794 714 dans l'agglomération, et forme l'aire urbaine la plus peuplée au monde. Située sur la côte est de l'île principale de l'archipel japonais, Honshū, Tokyo est l'une des quarante-sept préfectures du Japon. Principal centre politique de l'archipel depuis le XVIIe siècle, la ville accueille la plupart des institutions du pays.", "https://images.pexels.com/photos/1134166/pexels-photo-1134166.jpeg", "Tokyo", "Asie")
            article2 = Article("Denpasar","Denpasar est une kota (« ville ») de la province de Bali, au sud de l’Indonésie, dont elle est le « chef-lieu ». Denpasar est la seule ville de la province de Bali à détenir le statut de kota, subdivision de même niveau que le kabupaten (« département »). Elle est dirigée par un walikota (« maire ») élu par l'assemblée municipale, elle-même élue au suffrage direct. ", "https://images.pexels.com/photos/2166553/pexels-photo-2166553.jpeg", "Denpasar", "Asie")
            article3 = Article("Pékin","Pékin, ou Beijing, est la capitale de la République populaire de Chine. Située dans le Nord-Est du pays, la municipalité de Pékin, d'une superficie de 16 800 km2, est entourée par la province du Hebei ainsi que la municipalité de Tianjin. Pékin est considérée comme le centre politique et culturel de la Chine, tandis que Hong Kong et Shanghai dominent au niveau économique. D'abord ville périphérique de l'empire chinois sous les Han et les Tang, elle prend de l'importance lorsque les Jurchen, qui fondent la dynastie Jin, la choisissent comme leur capitale principale en 1153.", "https://images.pexels.com/photos/2846034/pexels-photo-2846034.jpeg", "Beijing", "Asie")
            article4 = Article("Sri Jayawardenapura Kotte","Sri Jayawardenapura Kotte, communément appelée Kotte, est la capitale administrative du Sri Lanka. Elle se trouve dans la banlieue sud-est de Colombo, capitale économique. Les deux cités font partie de la province de l'Ouest. Le nom « Kotte », ancien nom officiel, provient du tamoul, qui signifie « forteresse ». À cette époque, il faisait référence d'une part aux espaces situés au sud et à l'extérieur des douves, appelés Pitakotte, ce qui se traduit par « hors du fort » et d'autre part à la zone protégée par les remparts, Ethul Kotte, et qui signifie « à l'intérieur du fort ». ", "https://images.pexels.com/photos/1998438/pexels-photo-1998438.jpeg", "Kotte", "Asie")
            article5 = Article("Jérusalem","Jérusalem ou Salem, est une ville du Proche-Orient, qui tient une place centrale dans les religions juive, chrétienne et musulmane, aujourd'hui capitale d'Israël, et que les Palestiniens souhaiteraient comme capitale pour leur futur État. La ville s’étend sur 125,1 km2 pour une population de 936 400 habitants en 2019. La ville, chef-lieu du district de Jérusalem, est cosmopolite : s'y mêlent de nombreuses religions, peuples, groupes socio-économiques.", "https://images.pexels.com/photos/2087323/pexels-photo-2087323.jpeg", "Jerusalem", "Asie")
            article6 = Article("Dubaï","Dubaï est la première ville des Émirats arabes unis (devant la capitale fédérale Abou Dabi). Située sur le golfe Persique, elle est capitale de l'émirat de Dubaï, et compte plus de trois millions d'habitants. Elle forme, avec les villes de Charjah, Ajman et Oumm al Qaïwaïn, elles-mêmes capitales de leurs émirats respectifs, une agglomération qui dépasse 3,1 millions d'habitants en 2018. Dubaï est également le premier port du pays. ", "https://images.pexels.com/photos/3769312/pexels-photo-3769312.jpeg", "Dubai", "Asie")
            article7 = Article("Singapour","Singapour, en forme longue la république de Singapour , est une cité-État d'Asie du Sud-Est. Sa superficie est de 724,2 km2. Elle comprend 63 îles, dont la principale est Pulau Ujong (584,8 km2). Cette île est très densément urbanisée, mais la végétation luxuriante – même en plein centre-ville – a valu à Singapour le surnom de « ville jardin ». Cette abondance de verdure découle en partie d'un climat équatorial, uniformément chaud et orageux tout au long de l'année. Sa densité de population est la troisième plus élevée au monde (après Monaco et Macao). ", "https://images.pexels.com/photos/777059/pexels-photo-777059.jpeg", "Singapore", "Asie")
            article8 = Article("Moscou","Moscou est la capitale de la Russie et compte environ douze millions six cent mille habitants intra muros (2017) sur une superficie de 2 510 km2 ce qui en fait la ville la plus peuplée à la fois du pays et d'Europe. Sur le plan administratif Moscou fait partie du district fédéral central et a le statut de ville d'importance fédérale qui lui donne le même niveau d'autonomie que les autres sujets de la Russie. Elle est quasiment enclavée dans l'oblast de Moscou, mais en est administrativement indépendante. Ses habitants sont les Moscovites.", "https://images.pexels.com/photos/2816185/pexels-photo-2816185.jpeg", "Moscow", "Asie")
            article9 = Article("Saint-Pétersbourg","Saint-Pétersbourg est la deuxième plus grande ville de Russie par sa population, avec 5 281 579 habitants en 2017, après la capitale Moscou. Saint-Pétersbourg a le statut de ville d'importance fédérale. La ville est enclavée dans l'oblast de Léningrad, mais en est administrativement indépendante. Elle est située dans le Nord-Ouest du pays sur le delta de la Neva, au fond du golfe de Finlande, un espace maritime de la mer Baltique.", "https://images.pexels.com/photos/3301030/pexels-photo-3301030.jpeg", "Saint Petersburg", "Asie")
            article10 = Article("Istanbul","Istanbul ou Istamboula, appelé officiellement ainsi à partir de 1930 et auparavant Constantinople, est la plus grande ville et métropole de Turquie et la préfecture de la province homonyme, dont elle représente environ 50 % de la superficie mais plus de 97 % de la population. Quatre zones historiques de la ville sont inscrites sur la liste du patrimoine mondial de l'Unesco depuis 1985. Istanbul est le principal centre économique (pôle financier, commercial et industriel) de la Turquie mais aussi la capitale culturelle du pays. ", "https://images.pexels.com/photos/1549326/pexels-photo-1549326.jpeg", "Istanbul", "Asie")
            val list_asie = listOf<Article>(article1,article2,article3,article4,article5,article6,article7,article8,article9,article10)
            articleDb.saveArticles(list_asie)
            article1 = Article("Sydney","Sydney est la ville la plus peuplée d'Australie et du continent océanien, ainsi que la capitale de l'État de Nouvelle-Galles du Sud. Elle est située dans le Sud-Est du pays, sur les rives de la mer de Tasman. Avec une aire urbaine comprenant, en 2016, une population de 5,25 millions d'habitants1 sur près de 12 300 km2, Sydney se place devant Melbourne et Brisbane pour ce qui est du nombre d'habitants. Ses habitants s'appellent les Sydneyites ou Sydneysiders en anglais et les Sydnéens en français. ", "https://images.pexels.com/photos/995764/pexels-photo-995764.jpeg", "Sydney", "Océanie")
            article2 = Article("Melbourne","Melbourne est la capitale de l'État du Victoria, en Australie. Deuxième agglomération urbaine du pays après Sydney, le « Grand Melbourne » (Greater Melbourne) compte 4 485 211 habitants au recensement officiel de 2016. La ville est située sur la baie de Port Phillip, laquelle ouvre sur le détroit de Bass. Ses habitants sont les Melbourniens (Melburnians en anglais). Melbourne est un important centre commercial, industriel et culturel. La ville est souvent qualifiée de capitale « sportive et culturelle » de l'Australie.", "https://images.pexels.com/photos/3626248/pexels-photo-3626248.jpeg", "Melbourne", "Océanie")
            article3 = Article("Auckland","Auckland est la ville la plus peuplée de Nouvelle-Zélande. Située sur l'île du Nord, c'est la plus grande zone urbaine du pays, avec plus de 1 500 000 habitants — soit plus d'un quart de la population du pays. Les données démographiques indiquent qu'elle continuera à croître plus rapidement que le reste du pays. Auckland est également la ville du monde qui abrite le plus grand nombre de personnes d'origine polynésienne. ", "https://images.pexels.com/photos/5063807/pexels-photo-5063807.jpeg", "Auckland", "Océanie")
            article4 = Article("Queenstown","Queenstown est une ville néo-zélandaise de la région Otago au sud-ouest sur l'Île du Sud. La ville est construite autour d'une anse sur le lac Wakatipu, un long lac mince formé comme un boulon et a de spectaculaires vues sur les montagnes voisines. La ville est surtout connue des amateurs de sensations fortes (saut à l'élastique, rafting, hors-bord, parapente, parachute, etc.). Durant la saison hivernale, de nombreux skieurs viennent glisser sur les Remarkables, montagnes situées non loin de la ville. ", "https://images.pexels.com/photos/37650/new-zealand-lake-mountain-landscape-37650.jpeg", "Queenstown", "Océanie")
            article5 = Article("Suva","Suva est la capitale des Fidji. Elle comptait 74 481 habitants lors du recensement en 2007. En comptant les banlieues, la population de la zone urbaine de Suva était de 85 691 lors du même recensement. La grande agglomération compte presque 300 000 habitants, soit un tiers de la population totale de la république. Elle est située sur la côte sud-est de l'île de Viti Levu, dans la Division centrale des Fidji, dont elle est le centre administratif.", "https://images.pexels.com/photos/1752461/pexels-photo-1752461.jpeg", "Suva", "Océanie")
            article6 = Article("Perth","Perth est la capitale de l'État d'Australie-Occidentale. Elle est située dans le Sud-Ouest de l'Australie, en bordure de l'océan Indien et sur les rives du fleuve Swan. Sa population s'élève à 2 059 484 habitants en 2018, ce qui en fait la quatrième ville du pays. Fondée en 1829 par le capitaine James Stirling comme le premier point d'implantation d'une nouvelle colonie britannique, la Swan River Colony, Perth continue de servir comme siège du gouvernement de l'Australie-Occidentale jusqu'à aujourd'hui. ", "https://images.pexels.com/photos/3405467/pexels-photo-3405467.jpeg", "Perth", "Océanie")
            article7 = Article("Brisbane","Brisbane est la capitale et la ville la plus peuplée de l'État du Queensland, en Australie. Elle est située à 731 kilomètres au nord-nord-est de Sydney, à 1 375 kilomètres au nord-est de Melbourne, à 1 601 kilomètres à l'est-nord-est d'Adélaïde et à 3 608 kilomètres à l'est de Perth. Elle borde le fleuve Brisbane et s'étend sur une plaine humide bordée de collines, limitée par Moreton Bay et par les premiers contreforts de la cordillère australienne.", "https://images.pexels.com/photos/2314922/pexels-photo-2314922.jpeg", "Brisbane", "Océanie")
            article8 = Article("Gold Coast","Gold Coast est une conurbation australienne située le long de la côte pacifique formant la ville de Gold Coast, à environ 94 km au sud-est de Brisbane dans la région Sud-Est du Queensland en Australie. S'étendant sur une cinquantaine de kilomètres, cette agglomération de 538 263 habitants résulte d'un long processus de fusion communale entamé dans les années 1950. Elle constitue actuellement la sixième ville d'Australie et la deuxième du Queensland.", "https://images.pexels.com/photos/786357/pexels-photo-786357.jpeg", "Gold Coast", "Océanie")
            article9 = Article("Vaitape","Vaitape est une ville française située sur l'île de Bora-Bora, en Polynésie française dont elle constitue la principale agglomération avec 4 927 habitants en 2007. Elle se trouve à plus de 200 km de Papeete, le chef-lieu de la collectivité. Vaitape est le centre administratif de la commune de Bora-Bora regroupant l'île de Bora-Bora et l'atoll inhabité de Tupai. La ville est desservie par l'aéroport de Bora Bora. ", "https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg", "Vaitape", "Océanie")
            article10 = Article("Kokatahi","Kokatahi est situé dans la région de la West Coast située sur l'île du Sud de la Nouvelle-Zélande. Traversé par la rivière du même nom, qui est un affluent majeur de la rivière Hokitika. La rivière Kokatahi s’écoule vers le nord-ouest à partir de son origine sur les pentes nord du “Mount Ambrose” dans les Alpes du Sud atteignant la rivière Hokitika à 12 kilomètres de son embouchure au niveau de la ville d’Hokitika.", "https://images.pexels.com/photos/572689/pexels-photo-572689.jpeg", "Kokatahi", "Océanie")
            val list_oceanie = listOf<Article>(article1,article2,article3,article4,article5,article6,article7,article8,article9,article10)
            articleDb.saveArticles(list_oceanie)
        }
    }

    private fun query(continent : String): Array<Article> {
            return articleDb.requestArticleByContinent(continent).toTypedArray()
    }
}